apiVersion: v2
name: vsphere-csi-driver
# repo: kubernetes-sigs/vsphere-csi-driver
appVersion: 3.3.0
# repo: kubernetes-sigs/vsphere-csi-driver
version: 3.4.0
description: A Helm chart for vSphere CSI (Container Storage Interface) Driver
home: https://github.com/giantswarm/vsphere-csi-driver-app
keywords:
  - vsphere
  - vmware
  - csi
icon: https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/docs/vmware_logo.png
sources:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver
annotations:
  application.giantswarm.io/team: "rocket"
